version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgresql://hifor_database_user:Ylsg3mONeC29BUWosFz0gDshsJ1TyfTC@dpg-cum2spl6l47c7393qbpg-a.singapore-postgres.render.com/hifor_database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./event-images:/app/event-images
      - ./profile-images:/app/profile-images

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
