version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://hifor_database_user:Ylsg3mONeC29BUWosFz0gDshsJ1TyfTC@dpg-cum2spl6l47c7393qbpg-a.singapore-postgres.render.com/hifor_database?sslmode=require
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UPLOADS_PATH=/app/uploads
    volumes:
      - ./uploads:/app/uploads

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
    driver: local
