version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./event-images:/app/event-images
      - ./profile-images:/app/profile-images  # 프로필 이미지 저장 폴더 추가
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
